name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql, dom, gd, imagick, zip
        ini-values: post_max_size=256M, upload_max_filesize=256M
        tools: composer

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Create database (SQLite)
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run migrations
      run: php artisan migrate --force

    - name: Install PHP CodeSniffer for linting
      run: composer require --dev squizlabs/php_codesniffer

    - name: Run PHP CodeSniffer (Linting)
      run: ./vendor/bin/phpcs --report=checkstyle --report-file=phpcs-report.xml || true

    - name: Run PHP Stan (Static Analysis)
      run: |
        composer require --dev phpstan/phpstan
        ./vendor/bin/phpstan analyse --configuration=phpstan.neon --error-format=checkstyle > phpstan-report.xml || true

    - name: Install Local PHP Security Checker
      run: |
        curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.6/local-php-security-checker_2.0.6_linux_amd64 -o local-php-security-checker
        chmod +x local-php-security-checker

    - name: Run Security Audit (Local PHP Security Checker)
      run: ./local-php-security-checker --format=json --output=security-report.json || true

    - name: Run Composer Security Audit
      run: composer audit --format=json > composer-audit.json || true

    - name: Install and Run PHPStan Security Analysis
      run: |
        composer require --dev phpstan/phpstan-symfony
        ./vendor/bin/phpstan analyse --configuration=phpstan.neon --error-format=json > phpstan-security.json || true

    - name: Run tests with coverage
      run: php artisan test --coverage --coverage-clover=coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Notify success
      if: success()
      env:
        GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -d '{
          "text": "✅ *Laravel CI Pipeline PASSED* ✅\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Commit Message:* ${{ github.event.head_commit.message }}\n*Author:* ${{ github.actor }}\n*Workflow:* ${{ github.workflow }}\n*Run ID:* ${{ github.run_id }}\n\n🎉 All tests passed successfully!"
        }' \
        "$GOOGLE_CHAT_WEBHOOK"

    - name: Notify failure
      if: failure()
      env:
        GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -d '{
          "text": "❌ *Laravel CI Pipeline FAILED* ❌\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Commit Message:* ${{ github.event.head_commit.message }}\n*Author:* ${{ github.actor }}\n*Workflow:* ${{ github.workflow }}\n*Run ID:* ${{ github.run_id }}\n\n💥 Pipeline failed. Please check the logs for details.\n\n[View Run Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        }' \
        "$GOOGLE_CHAT_WEBHOOK"